"""fiexd table names

Revision ID: a293f8e5b1c1
Revises: 8e52498f446b
Create Date: 2026-07-14 11:38:49.513992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a293f8e5b1c1'
down_revision: Union[str, None] = '8e52498f446b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('volumes_published', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('edition', sa.String(length=20), nullable=False),
    sa.Column('number_of_copies', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_book_book_id'), 'book', ['book_id'], unique=False)
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_index(op.f('ix_genre_genre_id'), 'genre', ['genre_id'], unique=False)
    op.create_table('penalty',
    sa.Column('penalty_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('number_of_weeks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('penalty_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=21), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('book_genre_association',
    sa.Column('book_genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_genre_id')
    )
    op.create_table('borrow_from_user',
    sa.Column('borrow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('borrowed_from', sa.Date(), nullable=False),
    sa.Column('borrowed_until', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('borrow_id')
    )
    op.create_table('borrow_to_user',
    sa.Column('borrow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('borrowed_from', sa.Date(), nullable=False),
    sa.Column('borrowed_until', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('borrow_id')
    )
    op.create_table('penalties_to_user',
    sa.Column('user_penalty_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('penalty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['penalty_id'], ['penalty.penalty_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_penalty_id')
    )
    op.create_table('written_by',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('written_by')
    op.drop_table('penalties_to_user')
    op.drop_table('borrow_to_user')
    op.drop_table('borrow_from_user')
    op.drop_table('book_genre_association')
    op.drop_table('user')
    op.drop_table('penalty')
    op.drop_index(op.f('ix_genre_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_book_book_id'), table_name='book')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
