"""updatead database and imports

Revision ID: 4b43d717310b
Revises: eaa4c7ff7ae7
Create Date: 2026-07-14 08:37:01.686611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b43d717310b'
down_revision: Union[str, None] = 'eaa4c7ff7ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('edition', sa.String(length=20), nullable=False),
    sa.Column('number_of_copies', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_books_book_id'), 'books', ['book_id'], unique=False)
    op.create_table('penalties',
    sa.Column('penalty_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('number_of_weeks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('penalty_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=21), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('book_genre_associations',
    sa.Column('book_genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_genre_id')
    )
    op.create_table('borrow_from_users',
    sa.Column('borrow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('borrowed_from', sa.Date(), nullable=False),
    sa.Column('borrowed_until', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('borrow_id')
    )
    op.create_table('borrow_to_users',
    sa.Column('borrow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('borrowed_from', sa.Date(), nullable=False),
    sa.Column('borrowed_until', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('borrow_id')
    )
    op.create_table('penalties_to_users',
    sa.Column('user_penalty_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('penalty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['penalty_id'], ['penalties.penalty_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_penalty_id')
    )
    op.create_table('written_by',
    sa.Column('writtenby_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('writtenby_id')
    )
    op.drop_index(op.f('ix_Books_book_id'), table_name='Books')
    op.drop_table('Books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('book_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('edition', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('number_of_copies', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('book_id', name=op.f('Books_pkey'))
    )
    op.create_index(op.f('ix_Books_book_id'), 'Books', ['book_id'], unique=False)
    op.drop_table('written_by')
    op.drop_table('penalties_to_users')
    op.drop_table('borrow_to_users')
    op.drop_table('borrow_from_users')
    op.drop_table('book_genre_associations')
    op.drop_table('users')
    op.drop_table('penalties')
    op.drop_index(op.f('ix_books_book_id'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
