"""resolved first migration

Revision ID: 6f9d10ada438
Revises: 33f15affd738
Create Date: 2026-07-13 13:48:14.217976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9d10ada438'
down_revision: Union[str, None] = '33f15affd738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('book_id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('edition', sa.String(length=20), nullable=False),
    sa.Column('number_of_copies', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_Books_book_id'), 'Books', ['book_id'], unique=False)
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_index(op.f('ix_genres_genre_id'), 'genres', ['genre_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genres_genre_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_Books_book_id'), table_name='Books')
    op.drop_table('Books')
    # ### end Alembic commands ###
