"""first migration

Revision ID: 8e52498f446b
Revises: 
Create Date: 2026-07-13 11:07:32.181423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e52498f446b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('example_field_1', sa.String(), nullable=True),
    sa.Column('example_field_2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Test_id'), 'Test', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Test_id'), table_name='Test')
    op.drop_table('Test')
    # ### end Alembic commands ###
