"""added author model

Revision ID: 9ee58528194d
Revises: 6f9d10ada438
Create Date: 2026-07-13 14:39:05.214757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee58528194d'
down_revision: Union[str, None] = '6f9d10ada438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('volumes_published', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###
